jobs:
  - name: test
    max_in_flight: 1
    public: true
    plan:
      - get: resource-tutorial
        trigger: true
      - task: run-test-staging
        file: resource-tutorial/ci/unit_testing.yml

  - name: build
    max_in_flight: 1
    public: true
    plan:
      - get: resource-tutorial
        trigger: true
        passed: [ test ]
      - task: run-build-staging
        file: resource-tutorial/ci/build_staging.yml
      - put: distribution_appcenter
        inputs:
          - generatedAPK
        params:
          path: generatedAPK
          binary_name: app-debug.apk

  - name: notify-slack
    plan:
      - put: slack-alert
      - put: distribution_appcenter
        params:
          channel: ((slack-channel))
          text: |
           The reports are:
            http://my.concourse.url/teams/$BUILD_TEAM_NAME
          attachment_file: app/build/outputs/test/testDebugUnitTest/index.html

#############
# RESOURCES #
#############
resources:
  - icon: github
    name: resource-tutorial
    type: git
    source:
      uri: https://github.com/giovas17/ComposeExample.git
      branch: feature/adding_concourse_ci

  #- icon: github
  #  name: resource-tutorial-pull-request
  #  type: pull-request
  #  source:
  #    uri: https://github.com/giovas17/ComposeExample.git
  #    branch: develop

  - name: slack-alert
    type: slack-notification
    source:
      url: ((slack-hook-url))

  - name: distribution_appcenter
    type: appcenter
    source:
      api_token: ((appcenter-api_token))
      owner: ((appcenter-owner))
      app_name: ((appcenter-app_name))
      group_id: ((appcenter-group_id))

##################
# RESOURCE_TYPES #
##################
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

  - name: appcenter
    type: docker-image
    source:
      repository: tomoyukim/concourse-appcenter-resource
      tag: latest

  #- name: pull-request
  #  type: docker-image
  #  source:
  #    repository: jtarchie/pr