---
task-config: &task-config
  platform: linux
  caches:
    - path: $HOME/.m2/repository
    - path: $HOME/.gradle/caches/
    - path: $HOME/.gradle/wrapper/
  image_resource:
    type: registry-image
    source:
      repository: gradle
      tag: jdk8-slim
  inputs:
    - name: content-generator
  outputs:
    - name: files

jobs:
  - name: test
    max_in_flight: 1
    public: true
    plan:
      - get: resource-tutorial
        trigger: true
      - task: run-test-staging
        file: resource-tutorial/ci/unit_testing.yml

  - name: build
    max_in_flight: 1
    public: true
    plan:
      - get: resource-tutorial
        trigger: true
        passed: [ test ]
      - task: run-build-staging
        file: resource-tutorial/ci/build_staging.yml
        on_success:
          do:
            - get: content-generator
            - task: create-slack-content
              file: resource-tutorial/ci/slack_content_creator.yml
              params:
                TYPE: Build
                STATE: Success
                MESSAGE: 'The build has been created successfully'
                LINK: "${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
              on_success:
                put: slack-alert
                params:
                  text: "Build ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME} #${BUILD_NAME}"
                  attachments_file: ./files/created_file.json
      - put: distribution_appcenter
        inputs:
          - generatedAPK
        params:
          path: generatedAPK
          binary_name: app-debug.apk

  - name: create-file-slack
    plan:
      - get: content-generator
      - task: make-a-file
        config:
          << : *task-config
          run:
            path: sh
            user: root
            args:
              - -c
              - |
                ls -la
                export build_root=$(pwd)
                cd content-generator/
                echo '' > ${build_root}/files/created_file.json
                ./gradlew run --args="Slack build success 'The build is successfully created' http://localhost:8080/teams/main/pipelines/concourse_example/jobs/create-file-slack/builds/13 ${build_root}/files/created_file.json"

      - task: read-file
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          inputs:
            - name: files
          run:
            path: cat
            args:
              - ./files/created_file.json
        on_success:
          put: slack-alert
          params:
            text: "Build ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME} #${BUILD_NAME}"
            attachments_file: ./files/created_file.json

  - name: notify-slack
    plan:
      - put: slack-alert
        params:
          channel: ((slack-channel))
          attachment_file: app/build/outputs/test/testDebugUnitTest/index.html

#############
# RESOURCES #
#############
resources:
  - icon: github
    name: resource-tutorial
    type: git
    source:
      uri: https://github.com/giovas17/ComposeExample.git
      branch: feature/adding_concourse_ci

  - icon: github
    name: content-generator
    type: git
    source:
      uri: https://github.com/giovas17/Content-Alert-Creator.git
      branch: master

  #- icon: github
  #  name: resource-tutorial-pull-request
  #  type: pull-request
  #  source:
  #    uri: https://github.com/giovas17/ComposeExample.git
  #    branch: develop

  - name: slack-alert
    type: slack-notification
    source:
      url: ((slack-hook-url))

  - name: distribution_appcenter
    type: appcenter
    source:
      api_token: ((appcenter-api_token))
      owner: ((appcenter-owner))
      app_name: ((appcenter-app_name))
      group_id: ((appcenter-group_id))

##################
# RESOURCE_TYPES #
##################
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

  - name: appcenter
    type: docker-image
    source:
      repository: tomoyukim/concourse-appcenter-resource
      tag: latest

  #- name: pull-request
  #  type: docker-image
  #  source:
  #    repository: jtarchie/pr