resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/giovas17/ComposeExample.git
      branch: feature/adding_concourse_ci

jobs:
  - name: build
    max_in_flight: 1
    public: true
    plan:
      - get: resource-tutorial
      - task: run-build-staging
        config:
          caches:
            - path: $HOME/.gradle/
            - path: $HOME/.m2/repository
          params:
            TERM: dumb
          platform: linux
          inputs:
            - name: resource-tutorial
          image_resource:
            type: docker-image
            source:
              repository: darkgeat/android-studio-gitlab-ci
              tag: '2.0.0'
          run:
            dir: resource-tutorial
            path: ./gradlew
            user: root
            args:
              - 'assembleDebug'
              - '--stacktrace'
              - '--debug'
